FROM python:3.11-slim

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install the dependencies
RUN pip install langchain-mcp-adapters pikepdf  pdfx

# Copy the application code
COPY . .

# Expose the port for the Flask application


# Run the command to start the development server when the container starts
CMD ["python", "server.py"]
